### ISSUE TITLE
Project update

### ISSUE THREAD

**Issue by npomfret** [agrass/react-native-gps#1]
hi - what is the state of this project.  it looks really interesting - does it work on both IOS and Android?

**Comment by agrass** [comment]
Hi @npomfret ,

It work for IOS and Android but only the a basic subscription to location updates for the moment. There are not too much difference with [Geolocation API](https://facebook.github.io/react-native/docs/geolocation.html#content); but the idea is to create more config methods to make it a worthwhile project.

**Comment by npomfret** [comment]
Thanks for the reply.  Great work.

**Comment by agrass** [comment]
;)
