### ISSUE TITLE
On Android the startUpdatingLocation() is not triggered

### ISSUE THREAD

**Issue by himelnagrana** [agrass/react-native-gps#10]
Hi There,
First of all thanks for the solution. It's promising and helpful.

I think I might be missing something as my implementation doesn't trigger the `startUpdatingLocation()` automatically so while being subscribed to listener - I am not receiving location.

My Implementation:

```
if (Platform.OS == 'ios') {
    Location.requestAlwaysAuthorization();
    Location.startUpdatingLocation();
    Location.setDistanceFilter(5.0);
} else {
    Location.requestWhenInUseAuthorization();
    Location.startUpdatingLocation();
}

var subscription = DeviceEventEmitter.addListener(
    'locationUpdated',
        (location) => {
            console.log(location);
        }
);
```

In Android Emulator if I click "**Send**" from settings - it received location. In iOS it works fine.
Please suggest me where I am doing wrong.

Thanks.

**Comment by agrass** [comment]
Hi @himelnagrana! did you fix this issue? Which version of RN are you using?

**Comment by himelnagrana** [comment]
No. Unfortunately I was not able to fix this. Rather i did some hackish solution to detect automatic firt call from ios and ignored it in code. That way the two platform behaved equally.

I know it's changing the design but it is the way it is.

Thanks.

**Comment by Moussawi7** [comment]
Same issue here, Did you find a solution?

**Comment by stsiushkevich** [comment]
I have the same issue. I use React Native 0.42.0

**Comment by YazilimTuneli** [comment]
Did you find a solution?

**Comment by alineo7** [comment]
@YazilimTuneli ,
in fact i switched to this repo:
https://github.com/MustansirZia/react-native-fused-location
