### ISSUE TITLE
App on android > 22 craches

### ISSUE THREAD

**Issue by haelsisy** [agrass/react-native-gps#12]
App on android > 22 crashes because of new permissions system

![screenshot_1509998166](https://user-images.githubusercontent.com/11634587/32461054-4d44462a-c33d-11e7-929d-c98b124a01d6.png)

**Comment by milon87** [comment]
I think it requires Run Time permission

**Comment by agrass** [comment]
@zumaawad did you be able to solve this?? Have you the permissions on the Android manifest?
