### ISSUE TITLE
Error on react-native run-android

### ISSUE THREAD

**Issue by f0ntana** [agrass/react-native-gps#15]
`react-native-cli: 2.0.1
react-native: 0.45.1`

I do the config on readme and when i was goin run `react-native run-android`, i got this errors

> /Users/fontana/Developer/softsul/petrovina/petrovina-crm/mobile/android/app/src/main/java/com/petrovinacrm/MainActivity.java:18: error: cannot find symbol
    protected void onCreate(Bundle savedInstanceState) {
                            ^
  symbol:   class Bundle
  location: class MainActivity
/Users/fontana/Developer/softsul/petrovina/petrovina-crm/mobile/android/app/src/main/java/com/petrovinacrm/MainActivity.java:20: error: cannot find symbol
        mReactRootView = new ReactRootView(this);
        ^
  symbol:   variable mReactRootView
  location: class MainActivity
/Users/fontana/Developer/softsul/petrovina/petrovina-crm/mobile/android/app/src/main/java/com/petrovinacrm/MainActivity.java:20: error: cannot find symbol
        mReactRootView = new ReactRootView(this);
                             ^
  symbol:   class ReactRootView
  location: class MainActivity
/Users/fontana/Developer/softsul/petrovina/petrovina-crm/mobile/android/app/src/main/java/com/petrovinacrm/MainActivity.java:22: error: cannot find symbol
        mReactInstanceManager = ReactInstanceManager.builder()
        ^
  symbol:   variable mReactInstanceManager
  location: class MainActivity
/Users/fontana/Developer/softsul/petrovina/petrovina-crm/mobile/android/app/src/main/java/com/petrovinacrm/MainActivity.java:29: error: cannot find symbol
        .setInitialLifecycleState(LifecycleState.RESUMED)
                                  ^
  symbol:   variable LifecycleState
  location: class MainActivity
/Users/fontana/Developer/softsul/petrovina/petrovina-crm/mobile/android/app/src/main/java/com/petrovinacrm/MainActivity.java:26: error: cannot find symbol
        .addPackage(new MainReactPackage())
                        ^
  symbol:   class MainReactPackage
  location: class MainActivity
/Users/fontana/Developer/softsul/petrovina/petrovina-crm/mobile/android/app/src/main/java/com/petrovinacrm/MainActivity.java:22: error: cannot find symbol
        mReactInstanceManager = ReactInstanceManager.builder()
                                ^
  symbol:   variable ReactInstanceManager
  location: class MainActivity
/Users/fontana/Developer/softsul/petrovina/petrovina-crm/mobile/android/app/src/main/java/com/petrovinacrm/MainActivity.java:32: error: cannot find symbol
        mReactRootView.startReactApplication(mReactInstanceManager, "example", null);
                                             ^
  symbol:   variable mReactInstanceManager
  location: class MainActivity
/Users/fontana/Developer/softsul/petrovina/petrovina-crm/mobile/android/app/src/main/java/com/petrovinacrm/MainActivity.java:32: error: cannot find symbol
        mReactRootView.startReactApplication(mReactInstanceManager, "example", null);
        ^
  symbol:   variable mReactRootView
  location: class MainActivity
/Users/fontana/Developer/softsul/petrovina/petrovina-crm/mobile/android/app/src/main/java/com/petrovinacrm/MainActivity.java:34: error: cannot find symbol
        setContentView(mReactRootView);
                       ^
  symbol:   variable mReactRootView
  location: class MainActivity
10 errors
:app:compileDebugJavaWithJavac FAILED

`package com.petrovinacrm;

import com.facebook.react.ReactActivity;
import com.syarul.rnlocation.RNLocation;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "PetrovinaCRM";
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mReactRootView = new ReactRootView(this);

        mReactInstanceManager = ReactInstanceManager.builder()
        .setApplication(getApplication())
        .setBundleAssetName("index.android.bundle")
        .setJSMainModuleName("index.android")
        .addPackage(new MainReactPackage())
        .addPackage(new RNLocation())
        .setUseDeveloperSupport(BuildConfig.DEBUG)
        .setInitialLifecycleState(LifecycleState.RESUMED)
        .build();

        mReactRootView.startReactApplication(mReactInstanceManager, "example", null);

        setContentView(mReactRootView);
    }
}
`

**Comment by gpedro** [comment]
if you are using RN +0.40, follow step below instead docs step "register module (in MainActivity.java)"
```
    // MainApplication.java
    import com.syarul.rnlocation.RNLocation; // <--- import
    ...
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new RNLocation() // <-- Register package here
      );
    }

```

**Comment by f0ntana** [comment]
Thats resolve, thanks man
